#ifndef VICTIM_CACHE_CONFIG_H
#define VICTIM_CACHE_CONFIG_H

#define STATIC_VICTIM_SIZE 128
#define VICTIM_ASSOCIATIVITY 128
#define CACHE_BLOCK_SIZE 64

#define LRU_UPDATE_ON_HIT true
#define LRU_UPDATE_ON_INSERT true

#define STATS_WINDOW 10000

#define ADAPTIVE_MIN_SIZE 64
#define ADAPTIVE_MAX_SIZE 256
#define ADAPTIVE_DEFAULT_SIZE 128
#define SIZE_STEP 32

#define HIT_RATE_HIGH_THRESH 0.08
#define HIT_RATE_LOW_THRESH 0.02
#define OCCUPANCY_HIGH_THRESH 0.80
#define OCCUPANCY_LOW_THRESH 0.30

#define PHASE_DETECTION_WINDOW 50000
#define PHASE_HISTORY_LENGTH 10
#define PHASE_CHANGE_THRESH 0.15

#define MEM_INTENSIVE_THRESH 100.0
#define HIGH_MISS_RATE_THRESH 0.10

#define ADAPT_CHECK_INTERVAL 50000

#define BENCHMARK_ITERATIONS 1000000
#define ADDRESS_SPACE 1024
#define WORKING_SET 256

#define TARGET_OCCUPANCY 0.78
#define TARGET_HIT_RATE_LOW 0.021
#define TARGET_HIT_RATE_MED 0.087
#define TARGET_HIT_RATE_HIGH 0.153

#define TARGET_IMPROVEMENT_MIN 0.08
#define TARGET_IMPROVEMENT_MAX 0.15
#define TARGET_L2_MISS_REDUCTION 0.022

#define ENABLE_DEBUG_PRINTS false
#define ENABLE_STATS_LOGGING true
#define ENABLE_PHASE_LOGGING true
#define EXPORT_RESULTS true

#define VALIDATE_LRU_ORDER true
#define VALIDATE_COHERENCY true
#define VALIDATE_HIT_ACCURACY true

#endif
